project_id = "aseefhqhksblqagehklg"

[functions.create-restricted-user]
verify_jwt = false



[functions.seed-us-communications]
verify_jwt = false

[functions.seed-onboarding-tasks]
verify_jwt = false

[functions.seed-whatsapp-enhanced]
verify_jwt = false

[functions.seed-team-members]
verify_jwt = false

[functions.seed-demo-relationships]
verify_jwt = false

[functions.seed-calendar-events]
verify_jwt = false

[functions.seed-open-tasks]
verify_jwt = false

[functions.guess-email-tasks]
verify_jwt = false

[functions.seed-email-tasks]
verify_jwt = false

[functions.seed-notifications]
verify_jwt = false

[functions.seed-meeting-recordings]
verify_jwt = false

[functions.seed-meeting-prep-data]
verify_jwt = false

