import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// Reference data arrays
const currencies = [
  { code: "AED", name: "UAE Dirham", description: "United Arab Emirates" },
  { code: "AFN", name: "Afghan Afghani", description: "Afghanistan" },
  { code: "ALL", name: "Albanian Lek", description: "Albania" },
  { code: "AMD", name: "Armenian Dram", description: "Armenia" },
  { code: "ANG", name: "Netherlands Antillean Guilder", description: "Curaçao, Sint Maarten" },
  { code: "AOA", name: "Angolan Kwanza", description: "Angola" },
  { code: "ARS", name: "Argentine Peso", description: "Argentina" },
  { code: "AUD", name: "Australian Dollar", description: "Australia" },
  { code: "AWG", name: "Aruban Florin", description: "Aruba" },
  { code: "AZN", name: "Azerbaijani Manat", description: "Azerbaijan" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", description: "Bosnia and Herzegovina" },
  { code: "BBD", name: "Barbadian Dollar", description: "Barbados" },
  { code: "BDT", name: "Bangladeshi Taka", description: "Bangladesh" },
  { code: "BGN", name: "Bulgarian Lev", description: "Bulgaria" },
  { code: "BHD", name: "Bahraini Dinar", description: "Bahrain" },
  { code: "BIF", name: "Burundian Franc", description: "Burundi" },
  { code: "BMD", name: "Bermudian Dollar", description: "Bermuda" },
  { code: "BND", name: "Brunei Dollar", description: "Brunei" },
  { code: "BOB", name: "Bolivian Boliviano", description: "Bolivia" },
  { code: "BRL", name: "Brazilian Real", description: "Brazil" },
  { code: "BSD", name: "Bahamian Dollar", description: "Bahamas" },
  { code: "BTN", name: "Bhutanese Ngultrum", description: "Bhutan" },
  { code: "BWP", name: "Botswanan Pula", description: "Botswana" },
  { code: "BYN", name: "Belarusian Ruble", description: "Belarus" },
  { code: "BZD", name: "Belize Dollar", description: "Belize" },
  { code: "CAD", name: "Canadian Dollar", description: "Canada" },
  { code: "CDF", name: "Congolese Franc", description: "Democratic Republic of the Congo" },
  { code: "CHF", name: "Swiss Franc", description: "Switzerland" },
  { code: "CLP", name: "Chilean Peso", description: "Chile" },
  { code: "CNY", name: "Chinese Yuan", description: "China" },
  { code: "COP", name: "Colombian Peso", description: "Colombia" },
  { code: "CRC", name: "Costa Rican Colón", description: "Costa Rica" },
  { code: "CUP", name: "Cuban Peso", description: "Cuba" },
  { code: "CVE", name: "Cape Verdean Escudo", description: "Cape Verde" },
  { code: "CZK", name: "Czech Koruna", description: "Czech Republic" },
  { code: "DJF", name: "Djiboutian Franc", description: "Djibouti" },
  { code: "DKK", name: "Danish Krone", description: "Denmark" },
  { code: "DOP", name: "Dominican Peso", description: "Dominican Republic" },
  { code: "DZD", name: "Algerian Dinar", description: "Algeria" },
  { code: "EGP", name: "Egyptian Pound", description: "Egypt" },
  { code: "ERN", name: "Eritrean Nakfa", description: "Eritrea" },
  { code: "ETB", name: "Ethiopian Birr", description: "Ethiopia" },
  { code: "EUR", name: "Euro", description: "European Union" },
  { code: "FJD", name: "Fijian Dollar", description: "Fiji" },
  { code: "FKP", name: "Falkland Islands Pound", description: "Falkland Islands" },
  { code: "GBP", name: "British Pound Sterling", description: "United Kingdom" },
  { code: "GEL", name: "Georgian Lari", description: "Georgia" },
  { code: "GHS", name: "Ghanaian Cedi", description: "Ghana" },
  { code: "GIP", name: "Gibraltar Pound", description: "Gibraltar" },
  { code: "GMD", name: "Gambian Dalasi", description: "Gambia" },
  { code: "GNF", name: "Guinean Franc", description: "Guinea" },
  { code: "GTQ", name: "Guatemalan Quetzal", description: "Guatemala" },
  { code: "GYD", name: "Guyanese Dollar", description: "Guyana" },
  { code: "HKD", name: "Hong Kong Dollar", description: "Hong Kong" },
  { code: "HNL", name: "Honduran Lempira", description: "Honduras" },
  { code: "HRK", name: "Croatian Kuna", description: "Croatia" },
  { code: "HTG", name: "Haitian Gourde", description: "Haiti" },
  { code: "HUF", name: "Hungarian Forint", description: "Hungary" },
  { code: "IDR", name: "Indonesian Rupiah", description: "Indonesia" },
  { code: "ILS", name: "Israeli New Shekel", description: "Israel" },
  { code: "INR", name: "Indian Rupee", description: "India" },
  { code: "IQD", name: "Iraqi Dinar", description: "Iraq" },
  { code: "IRR", name: "Iranian Rial", description: "Iran" },
  { code: "ISK", name: "Icelandic Króna", description: "Iceland" },
  { code: "JMD", name: "Jamaican Dollar", description: "Jamaica" },
  { code: "JOD", name: "Jordanian Dinar", description: "Jordan" },
  { code: "JPY", name: "Japanese Yen", description: "Japan" },
  { code: "KES", name: "Kenyan Shilling", description: "Kenya" },
  { code: "KGS", name: "Kyrgystani Som", description: "Kyrgyzstan" },
  { code: "KHR", name: "Cambodian Riel", description: "Cambodia" },
  { code: "KMF", name: "Comorian Franc", description: "Comoros" },
  { code: "KPW", name: "North Korean Won", description: "North Korea" },
  { code: "KRW", name: "South Korean Won", description: "South Korea" },
  { code: "KWD", name: "Kuwaiti Dinar", description: "Kuwait" },
  { code: "KYD", name: "Cayman Islands Dollar", description: "Cayman Islands" },
  { code: "KZT", name: "Kazakhstani Tenge", description: "Kazakhstan" },
  { code: "LAK", name: "Lao Kip", description: "Laos" },
  { code: "LBP", name: "Lebanese Pound", description: "Lebanon" },
  { code: "LKR", name: "Sri Lankan Rupee", description: "Sri Lanka" },
  { code: "LRD", name: "Liberian Dollar", description: "Liberia" },
  { code: "LSL", name: "Lesotho Loti", description: "Lesotho" },
  { code: "LYD", name: "Libyan Dinar", description: "Libya" },
  { code: "MAD", name: "Moroccan Dirham", description: "Morocco" },
  { code: "MDL", name: "Moldovan Leu", description: "Moldova" },
  { code: "MGA", name: "Malagasy Ariary", description: "Madagascar" },
  { code: "MKD", name: "Macedonian Denar", description: "North Macedonia" },
  { code: "MMK", name: "Myanmar Kyat", description: "Myanmar" },
  { code: "MNT", name: "Mongolian Tugrik", description: "Mongolia" },
  { code: "MOP", name: "Macanese Pataca", description: "Macau" },
  { code: "MRU", name: "Mauritanian Ouguiya", description: "Mauritania" },
  { code: "MUR", name: "Mauritian Rupee", description: "Mauritius" },
  { code: "MVR", name: "Maldivian Rufiyaa", description: "Maldives" },
  { code: "MWK", name: "Malawian Kwacha", description: "Malawi" },
  { code: "MXN", name: "Mexican Peso", description: "Mexico" },
  { code: "MYR", name: "Malaysian Ringgit", description: "Malaysia" },
  { code: "MZN", name: "Mozambican Metical", description: "Mozambique" },
  { code: "NAD", name: "Namibian Dollar", description: "Namibia" },
  { code: "NGN", name: "Nigerian Naira", description: "Nigeria" },
  { code: "NIO", name: "Nicaraguan Córdoba", description: "Nicaragua" },
  { code: "NOK", name: "Norwegian Krone", description: "Norway" },
  { code: "NPR", name: "Nepalese Rupee", description: "Nepal" },
  { code: "NZD", name: "New Zealand Dollar", description: "New Zealand" },
  { code: "OMR", name: "Omani Rial", description: "Oman" },
  { code: "PAB", name: "Panamanian Balboa", description: "Panama" },
  { code: "PEN", name: "Peruvian Sol", description: "Peru" },
  { code: "PGK", name: "Papua New Guinean Kina", description: "Papua New Guinea" },
  { code: "PHP", name: "Philippine Peso", description: "Philippines" },
  { code: "PKR", name: "Pakistani Rupee", description: "Pakistan" },
  { code: "PLN", name: "Polish Zloty", description: "Poland" },
  { code: "PYG", name: "Paraguayan Guarani", description: "Paraguay" },
  { code: "QAR", name: "Qatari Riyal", description: "Qatar" },
  { code: "RON", name: "Romanian Leu", description: "Romania" },
  { code: "RSD", name: "Serbian Dinar", description: "Serbia" },
  { code: "RUB", name: "Russian Ruble", description: "Russia" },
  { code: "RWF", name: "Rwandan Franc", description: "Rwanda" },
  { code: "SAR", name: "Saudi Riyal", description: "Saudi Arabia" },
  { code: "SBD", name: "Solomon Islands Dollar", description: "Solomon Islands" },
  { code: "SCR", name: "Seychellois Rupee", description: "Seychelles" },
  { code: "SDG", name: "Sudanese Pound", description: "Sudan" },
  { code: "SEK", name: "Swedish Krona", description: "Sweden" },
  { code: "SGD", name: "Singapore Dollar", description: "Singapore" },
  { code: "SHP", name: "Saint Helena Pound", description: "Saint Helena" },
  { code: "SLL", name: "Sierra Leonean Leone", description: "Sierra Leone" },
  { code: "SOS", name: "Somali Shilling", description: "Somalia" },
  { code: "SRD", name: "Surinamese Dollar", description: "Suriname" },
  { code: "SSP", name: "South Sudanese Pound", description: "South Sudan" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", description: "São Tomé and Príncipe" },
  { code: "SVC", name: "Salvadoran Colón", description: "El Salvador" },
  { code: "SYP", name: "Syrian Pound", description: "Syria" },
  { code: "SZL", name: "Swazi Lilangeni", description: "Eswatini" },
  { code: "THB", name: "Thai Baht", description: "Thailand" },
  { code: "TJS", name: "Tajikistani Somoni", description: "Tajikistan" },
  { code: "TMT", name: "Turkmenistani Manat", description: "Turkmenistan" },
  { code: "TND", name: "Tunisian Dinar", description: "Tunisia" },
  { code: "TOP", name: "Tongan Paʻanga", description: "Tonga" },
  { code: "TRY", name: "Turkish Lira", description: "Turkey" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", description: "Trinidad and Tobago" },
  { code: "TWD", name: "New Taiwan Dollar", description: "Taiwan" },
  { code: "TZS", name: "Tanzanian Shilling", description: "Tanzania" },
  { code: "UAH", name: "Ukrainian Hryvnia", description: "Ukraine" },
  { code: "UGX", name: "Ugandan Shilling", description: "Uganda" },
  { code: "USD", name: "United States Dollar", description: "United States" },
  { code: "UYU", name: "Uruguayan Peso", description: "Uruguay" },
  { code: "UZS", name: "Uzbekistani Som", description: "Uzbekistan" },
  { code: "VES", name: "Venezuelan Bolívar Soberano", description: "Venezuela" },
  { code: "VND", name: "Vietnamese Dong", description: "Vietnam" },
  { code: "VUV", name: "Vanuatu Vatu", description: "Vanuatu" },
  { code: "WST", name: "Samoan Tala", description: "Samoa" },
  { code: "XAF", name: "Central African CFA Franc", description: "Central Africa" },
  { code: "XCD", name: "East Caribbean Dollar", description: "East Caribbean" },
  { code: "XOF", name: "West African CFA Franc", description: "West Africa" },
  { code: "XPF", name: "CFP Franc", description: "French Pacific" },
  { code: "YER", name: "Yemeni Rial", description: "Yemen" },
  { code: "ZAR", name: "South African Rand", description: "South Africa" },
  { code: "ZMW", name: "Zambian Kwacha", description: "Zambia" },
  { code: "ZWL", name: "Zimbabwean Dollar", description: "Zimbabwe" },
];

const banks = [
  // South African Banks
  { code: "ABSA", name: "ABSA Bank", description: "South Africa" },
  { code: "FNB", name: "First National Bank", description: "South Africa" },
  { code: "STD", name: "Standard Bank", description: "South Africa" },
  { code: "NED", name: "Nedbank", description: "South Africa" },
  { code: "CAP", name: "Capitec Bank", description: "South Africa" },
  { code: "INV", name: "Investec Bank", description: "South Africa" },
  { code: "AFBN", name: "African Bank", description: "South Africa" },
  { code: "DISC", name: "Discovery Bank", description: "South Africa" },
  { code: "TYMEBN", name: "TymeBank", description: "South Africa" },
  { code: "BIDV", name: "Bidvest Bank", description: "South Africa" },
  { code: "GRIND", name: "Grindrod Bank", description: "South Africa" },
  { code: "MERC", name: "Mercantile Bank", description: "South Africa" },
  { code: "SASA", name: "Sasfin Bank", description: "South Africa" },
  { code: "ITHALA", name: "Ithala Bank", description: "South Africa" },
  { code: "UBANK", name: "Ubank", description: "South Africa" },
  { code: "FINBND", name: "Finbond Group", description: "South Africa" },
  // United States Banks
  { code: "JPM", name: "JPMorgan Chase", description: "United States" },
  { code: "BOA", name: "Bank of America", description: "United States" },
  { code: "CITI", name: "Citibank", description: "United States" },
  { code: "WF", name: "Wells Fargo", description: "United States" },
  { code: "GS", name: "Goldman Sachs", description: "United States" },
  { code: "MS", name: "Morgan Stanley", description: "United States" },
  { code: "USB", name: "U.S. Bancorp", description: "United States" },
  { code: "PNC", name: "PNC Financial Services", description: "United States" },
  { code: "TD", name: "TD Bank", description: "United States / Canada" },
  { code: "CAPITAL", name: "Capital One", description: "United States" },
  { code: "AMER", name: "Ameriprise Financial", description: "United States" },
  { code: "BNY", name: "Bank of New York Mellon", description: "United States" },
  { code: "STATE", name: "State Street Corporation", description: "United States" },
  { code: "FIFTH", name: "Fifth Third Bank", description: "United States" },
  { code: "KEY", name: "KeyBank", description: "United States" },
  // United Kingdom Banks
  { code: "HSBC", name: "HSBC Holdings", description: "United Kingdom" },
  { code: "BARC", name: "Barclays", description: "United Kingdom" },
  { code: "LLOYDS", name: "Lloyds Banking Group", description: "United Kingdom" },
  { code: "NWG", name: "NatWest Group", description: "United Kingdom" },
  { code: "STAND", name: "Standard Chartered", description: "United Kingdom" },
  { code: "VIRGIN", name: "Virgin Money UK", description: "United Kingdom" },
  { code: "METRO", name: "Metro Bank", description: "United Kingdom" },
  { code: "MONZO", name: "Monzo Bank", description: "United Kingdom" },
  { code: "REVOLUT", name: "Revolut", description: "United Kingdom" },
  { code: "STARLING", name: "Starling Bank", description: "United Kingdom" },
  // European Banks
  { code: "DB", name: "Deutsche Bank", description: "Germany" },
  { code: "COMMER", name: "Commerzbank", description: "Germany" },
  { code: "BNPP", name: "BNP Paribas", description: "France" },
  { code: "SOCGEN", name: "Société Générale", description: "France" },
  { code: "CA", name: "Crédit Agricole", description: "France" },
  { code: "SANTANDER", name: "Banco Santander", description: "Spain" },
  { code: "BBVA", name: "BBVA", description: "Spain" },
  { code: "ING", name: "ING Group", description: "Netherlands" },
  { code: "ABN", name: "ABN AMRO", description: "Netherlands" },
  { code: "UBS", name: "UBS Group", description: "Switzerland" },
  { code: "CS", name: "Credit Suisse", description: "Switzerland" },
  { code: "UNICREDIT", name: "UniCredit", description: "Italy" },
  { code: "INTESA", name: "Intesa Sanpaolo", description: "Italy" },
  { code: "NORDEA", name: "Nordea", description: "Finland" },
  { code: "DANSKE", name: "Danske Bank", description: "Denmark" },
  { code: "SBANK", name: "Swedbank", description: "Sweden" },
  { code: "SEB", name: "SEB Group", description: "Sweden" },
  { code: "DNB", name: "DNB ASA", description: "Norway" },
  { code: "RABO", name: "Rabobank", description: "Netherlands" },
  { code: "ERSTE", name: "Erste Group", description: "Austria" },
  { code: "KBCG", name: "KBC Group", description: "Belgium" },
  // Asian Banks
  { code: "ICBC", name: "Industrial and Commercial Bank of China", description: "China" },
  { code: "CCB", name: "China Construction Bank", description: "China" },
  { code: "ABC", name: "Agricultural Bank of China", description: "China" },
  { code: "BOC", name: "Bank of China", description: "China" },
  { code: "CMB", name: "China Merchants Bank", description: "China" },
  { code: "MUFG", name: "MUFG Bank", description: "Japan" },
  { code: "SMBC", name: "Sumitomo Mitsui Banking Corporation", description: "Japan" },
  { code: "MIZUHO", name: "Mizuho Financial Group", description: "Japan" },
  { code: "NOMURA", name: "Nomura Holdings", description: "Japan" },
  { code: "DBS", name: "DBS Bank", description: "Singapore" },
  { code: "OCBC", name: "OCBC Bank", description: "Singapore" },
  { code: "UOB", name: "United Overseas Bank", description: "Singapore" },
  { code: "HKBK", name: "Bank of East Asia", description: "Hong Kong" },
  { code: "HANGSENG", name: "Hang Seng Bank", description: "Hong Kong" },
  { code: "SBI", name: "State Bank of India", description: "India" },
  { code: "HDFC", name: "HDFC Bank", description: "India" },
  { code: "ICICI", name: "ICICI Bank", description: "India" },
  { code: "AXIS", name: "Axis Bank", description: "India" },
  { code: "KOTA", name: "Kotak Mahindra Bank", description: "India" },
  { code: "MAYBANK", name: "Maybank", description: "Malaysia" },
  { code: "CIMB", name: "CIMB Bank", description: "Malaysia" },
  { code: "RHB", name: "RHB Bank", description: "Malaysia" },
  { code: "KBANK", name: "Kasikornbank", description: "Thailand" },
  { code: "SCB", name: "Siam Commercial Bank", description: "Thailand" },
  { code: "BCA", name: "Bank Central Asia", description: "Indonesia" },
  { code: "BRI", name: "Bank Rakyat Indonesia", description: "Indonesia" },
  { code: "MANDIRI", name: "Bank Mandiri", description: "Indonesia" },
  { code: "KB", name: "KB Kookmin Bank", description: "South Korea" },
  { code: "SHINHAN", name: "Shinhan Bank", description: "South Korea" },
  { code: "WOORI", name: "Woori Bank", description: "South Korea" },
  { code: "HANA", name: "Hana Bank", description: "South Korea" },
  // Australian Banks
  { code: "CBA", name: "Commonwealth Bank", description: "Australia" },
  { code: "WBANK", name: "Westpac", description: "Australia" },
  { code: "ANZ", name: "ANZ Bank", description: "Australia" },
  { code: "NAB", name: "National Australia Bank", description: "Australia" },
  { code: "MQG", name: "Macquarie Group", description: "Australia" },
  // Canadian Banks
  { code: "RBC", name: "Royal Bank of Canada", description: "Canada" },
  { code: "TDC", name: "Toronto-Dominion Bank", description: "Canada" },
  { code: "BNS", name: "Bank of Nova Scotia", description: "Canada" },
  { code: "BMO", name: "Bank of Montreal", description: "Canada" },
  { code: "CIBC", name: "Canadian Imperial Bank of Commerce", description: "Canada" },
  // Middle East Banks
  { code: "QNB", name: "Qatar National Bank", description: "Qatar" },
  { code: "FAB", name: "First Abu Dhabi Bank", description: "UAE" },
  { code: "ENBD", name: "Emirates NBD", description: "UAE" },
  { code: "ADCB", name: "Abu Dhabi Commercial Bank", description: "UAE" },
  { code: "SNB", name: "Saudi National Bank", description: "Saudi Arabia" },
  { code: "SAMBA", name: "Samba Financial Group", description: "Saudi Arabia" },
  { code: "RIYAD", name: "Riyad Bank", description: "Saudi Arabia" },
  { code: "NBK", name: "National Bank of Kuwait", description: "Kuwait" },
  // Latin American Banks
  { code: "ITAU", name: "Itaú Unibanco", description: "Brazil" },
  { code: "BRAD", name: "Bradesco", description: "Brazil" },
  { code: "BDB", name: "Banco do Brasil", description: "Brazil" },
  { code: "NUBNK", name: "Nubank", description: "Brazil" },
  { code: "BANCHILE", name: "Banco de Chile", description: "Chile" },
  { code: "BCOL", name: "Bancolombia", description: "Colombia" },
  { code: "BANORTE", name: "Banorte", description: "Mexico" },
  // African Banks (beyond SA)
  { code: "ECOBANK", name: "Ecobank", description: "Pan-African" },
  { code: "STANBIC", name: "Stanbic Bank", description: "Pan-African" },
  { code: "EQUITY", name: "Equity Bank", description: "Kenya" },
  { code: "KCB", name: "Kenya Commercial Bank", description: "Kenya" },
  { code: "GTB", name: "Guaranty Trust Bank", description: "Nigeria" },
  { code: "ZENITH", name: "Zenith Bank", description: "Nigeria" },
  { code: "FBN", name: "First Bank of Nigeria", description: "Nigeria" },
  { code: "ACCESS", name: "Access Bank", description: "Nigeria" },
  { code: "UBA", name: "United Bank for Africa", description: "Nigeria" },
  { code: "CRDB", name: "CRDB Bank", description: "Tanzania" },
  { code: "BANMSR", name: "Banque Misr", description: "Egypt" },
  { code: "CIB", name: "Commercial International Bank", description: "Egypt" },
  { code: "NBE", name: "National Bank of Egypt", description: "Egypt" },
  { code: "ATTIJARIWAFA", name: "Attijariwafa Bank", description: "Morocco" },
  { code: "BMCE", name: "Bank of Africa", description: "Morocco" },
];

const locations = [
  { code: "AF", name: "Afghanistan", description: "Islamic Republic of Afghanistan" },
  { code: "AL", name: "Albania", description: "Republic of Albania" },
  { code: "DZ", name: "Algeria", description: "People's Democratic Republic of Algeria" },
  { code: "AD", name: "Andorra", description: "Principality of Andorra" },
  { code: "AO", name: "Angola", description: "Republic of Angola" },
  { code: "AG", name: "Antigua and Barbuda", description: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina", description: "Argentine Republic" },
  { code: "AM", name: "Armenia", description: "Republic of Armenia" },
  { code: "AU", name: "Australia", description: "Commonwealth of Australia" },
  { code: "AT", name: "Austria", description: "Republic of Austria" },
  { code: "AZ", name: "Azerbaijan", description: "Republic of Azerbaijan" },
  { code: "BS", name: "Bahamas", description: "Commonwealth of The Bahamas" },
  { code: "BH", name: "Bahrain", description: "Kingdom of Bahrain" },
  { code: "BD", name: "Bangladesh", description: "People's Republic of Bangladesh" },
  { code: "BB", name: "Barbados", description: "Barbados" },
  { code: "BY", name: "Belarus", description: "Republic of Belarus" },
  { code: "BE", name: "Belgium", description: "Kingdom of Belgium" },
  { code: "BZ", name: "Belize", description: "Belize" },
  { code: "BJ", name: "Benin", description: "Republic of Benin" },
  { code: "BT", name: "Bhutan", description: "Kingdom of Bhutan" },
  { code: "BO", name: "Bolivia", description: "Plurinational State of Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina", description: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana", description: "Republic of Botswana" },
  { code: "BR", name: "Brazil", description: "Federative Republic of Brazil" },
  { code: "BN", name: "Brunei", description: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria", description: "Republic of Bulgaria" },
  { code: "BF", name: "Burkina Faso", description: "Burkina Faso" },
  { code: "BI", name: "Burundi", description: "Republic of Burundi" },
  { code: "CV", name: "Cabo Verde", description: "Republic of Cabo Verde" },
  { code: "KH", name: "Cambodia", description: "Kingdom of Cambodia" },
  { code: "CM", name: "Cameroon", description: "Republic of Cameroon" },
  { code: "CA", name: "Canada", description: "Canada" },
  { code: "CF", name: "Central African Republic", description: "Central African Republic" },
  { code: "TD", name: "Chad", description: "Republic of Chad" },
  { code: "CL", name: "Chile", description: "Republic of Chile" },
  { code: "CN", name: "China", description: "People's Republic of China" },
  { code: "CO", name: "Colombia", description: "Republic of Colombia" },
  { code: "KM", name: "Comoros", description: "Union of the Comoros" },
  { code: "CG", name: "Congo", description: "Republic of the Congo" },
  { code: "CD", name: "Congo (DRC)", description: "Democratic Republic of the Congo" },
  { code: "CR", name: "Costa Rica", description: "Republic of Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire", description: "Republic of Côte d'Ivoire" },
  { code: "HR", name: "Croatia", description: "Republic of Croatia" },
  { code: "CU", name: "Cuba", description: "Republic of Cuba" },
  { code: "CY", name: "Cyprus", description: "Republic of Cyprus" },
  { code: "CZ", name: "Czech Republic", description: "Czech Republic" },
  { code: "DK", name: "Denmark", description: "Kingdom of Denmark" },
  { code: "DJ", name: "Djibouti", description: "Republic of Djibouti" },
  { code: "DM", name: "Dominica", description: "Commonwealth of Dominica" },
  { code: "DO", name: "Dominican Republic", description: "Dominican Republic" },
  { code: "EC", name: "Ecuador", description: "Republic of Ecuador" },
  { code: "EG", name: "Egypt", description: "Arab Republic of Egypt" },
  { code: "SV", name: "El Salvador", description: "Republic of El Salvador" },
  { code: "GQ", name: "Equatorial Guinea", description: "Republic of Equatorial Guinea" },
  { code: "ER", name: "Eritrea", description: "State of Eritrea" },
  { code: "EE", name: "Estonia", description: "Republic of Estonia" },
  { code: "SZ", name: "Eswatini", description: "Kingdom of Eswatini" },
  { code: "ET", name: "Ethiopia", description: "Federal Democratic Republic of Ethiopia" },
  { code: "FJ", name: "Fiji", description: "Republic of Fiji" },
  { code: "FI", name: "Finland", description: "Republic of Finland" },
  { code: "FR", name: "France", description: "French Republic" },
  { code: "GA", name: "Gabon", description: "Gabonese Republic" },
  { code: "GM", name: "Gambia", description: "Republic of The Gambia" },
  { code: "GE", name: "Georgia", description: "Georgia" },
  { code: "DE", name: "Germany", description: "Federal Republic of Germany" },
  { code: "GH", name: "Ghana", description: "Republic of Ghana" },
  { code: "GR", name: "Greece", description: "Hellenic Republic" },
  { code: "GD", name: "Grenada", description: "Grenada" },
  { code: "GT", name: "Guatemala", description: "Republic of Guatemala" },
  { code: "GN", name: "Guinea", description: "Republic of Guinea" },
  { code: "GW", name: "Guinea-Bissau", description: "Republic of Guinea-Bissau" },
  { code: "GY", name: "Guyana", description: "Co-operative Republic of Guyana" },
  { code: "HT", name: "Haiti", description: "Republic of Haiti" },
  { code: "HN", name: "Honduras", description: "Republic of Honduras" },
  { code: "HU", name: "Hungary", description: "Hungary" },
  { code: "IS", name: "Iceland", description: "Iceland" },
  { code: "IN", name: "India", description: "Republic of India" },
  { code: "ID", name: "Indonesia", description: "Republic of Indonesia" },
  { code: "IR", name: "Iran", description: "Islamic Republic of Iran" },
  { code: "IQ", name: "Iraq", description: "Republic of Iraq" },
  { code: "IE", name: "Ireland", description: "Republic of Ireland" },
  { code: "IL", name: "Israel", description: "State of Israel" },
  { code: "IT", name: "Italy", description: "Italian Republic" },
  { code: "JM", name: "Jamaica", description: "Jamaica" },
  { code: "JP", name: "Japan", description: "Japan" },
  { code: "JO", name: "Jordan", description: "Hashemite Kingdom of Jordan" },
  { code: "KZ", name: "Kazakhstan", description: "Republic of Kazakhstan" },
  { code: "KE", name: "Kenya", description: "Republic of Kenya" },
  { code: "KI", name: "Kiribati", description: "Republic of Kiribati" },
  { code: "KP", name: "North Korea", description: "Democratic People's Republic of Korea" },
  { code: "KR", name: "South Korea", description: "Republic of Korea" },
  { code: "KW", name: "Kuwait", description: "State of Kuwait" },
  { code: "KG", name: "Kyrgyzstan", description: "Kyrgyz Republic" },
  { code: "LA", name: "Laos", description: "Lao People's Democratic Republic" },
  { code: "LV", name: "Latvia", description: "Republic of Latvia" },
  { code: "LB", name: "Lebanon", description: "Lebanese Republic" },
  { code: "LS", name: "Lesotho", description: "Kingdom of Lesotho" },
  { code: "LR", name: "Liberia", description: "Republic of Liberia" },
  { code: "LY", name: "Libya", description: "State of Libya" },
  { code: "LI", name: "Liechtenstein", description: "Principality of Liechtenstein" },
  { code: "LT", name: "Lithuania", description: "Republic of Lithuania" },
  { code: "LU", name: "Luxembourg", description: "Grand Duchy of Luxembourg" },
  { code: "MG", name: "Madagascar", description: "Republic of Madagascar" },
  { code: "MW", name: "Malawi", description: "Republic of Malawi" },
  { code: "MY", name: "Malaysia", description: "Malaysia" },
  { code: "MV", name: "Maldives", description: "Republic of Maldives" },
  { code: "ML", name: "Mali", description: "Republic of Mali" },
  { code: "MT", name: "Malta", description: "Republic of Malta" },
  { code: "MH", name: "Marshall Islands", description: "Republic of the Marshall Islands" },
  { code: "MR", name: "Mauritania", description: "Islamic Republic of Mauritania" },
  { code: "MU", name: "Mauritius", description: "Republic of Mauritius" },
  { code: "MX", name: "Mexico", description: "United Mexican States" },
  { code: "FM", name: "Micronesia", description: "Federated States of Micronesia" },
  { code: "MD", name: "Moldova", description: "Republic of Moldova" },
  { code: "MC", name: "Monaco", description: "Principality of Monaco" },
  { code: "MN", name: "Mongolia", description: "Mongolia" },
  { code: "ME", name: "Montenegro", description: "Montenegro" },
  { code: "MA", name: "Morocco", description: "Kingdom of Morocco" },
  { code: "MZ", name: "Mozambique", description: "Republic of Mozambique" },
  { code: "MM", name: "Myanmar", description: "Republic of the Union of Myanmar" },
  { code: "NA", name: "Namibia", description: "Republic of Namibia" },
  { code: "NR", name: "Nauru", description: "Republic of Nauru" },
  { code: "NP", name: "Nepal", description: "Federal Democratic Republic of Nepal" },
  { code: "NL", name: "Netherlands", description: "Kingdom of the Netherlands" },
  { code: "NZ", name: "New Zealand", description: "New Zealand" },
  { code: "NI", name: "Nicaragua", description: "Republic of Nicaragua" },
  { code: "NE", name: "Niger", description: "Republic of the Niger" },
  { code: "NG", name: "Nigeria", description: "Federal Republic of Nigeria" },
  { code: "MK", name: "North Macedonia", description: "Republic of North Macedonia" },
  { code: "NO", name: "Norway", description: "Kingdom of Norway" },
  { code: "OM", name: "Oman", description: "Sultanate of Oman" },
  { code: "PK", name: "Pakistan", description: "Islamic Republic of Pakistan" },
  { code: "PW", name: "Palau", description: "Republic of Palau" },
  { code: "PS", name: "Palestine", description: "State of Palestine" },
  { code: "PA", name: "Panama", description: "Republic of Panama" },
  { code: "PG", name: "Papua New Guinea", description: "Independent State of Papua New Guinea" },
  { code: "PY", name: "Paraguay", description: "Republic of Paraguay" },
  { code: "PE", name: "Peru", description: "Republic of Peru" },
  { code: "PH", name: "Philippines", description: "Republic of the Philippines" },
  { code: "PL", name: "Poland", description: "Republic of Poland" },
  { code: "PT", name: "Portugal", description: "Portuguese Republic" },
  { code: "QA", name: "Qatar", description: "State of Qatar" },
  { code: "RO", name: "Romania", description: "Romania" },
  { code: "RU", name: "Russia", description: "Russian Federation" },
  { code: "RW", name: "Rwanda", description: "Republic of Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis", description: "Federation of Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia", description: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines", description: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa", description: "Independent State of Samoa" },
  { code: "SM", name: "San Marino", description: "Republic of San Marino" },
  { code: "ST", name: "Sao Tome and Principe", description: "Democratic Republic of São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia", description: "Kingdom of Saudi Arabia" },
  { code: "SN", name: "Senegal", description: "Republic of Senegal" },
  { code: "RS", name: "Serbia", description: "Republic of Serbia" },
  { code: "SC", name: "Seychelles", description: "Republic of Seychelles" },
  { code: "SL", name: "Sierra Leone", description: "Republic of Sierra Leone" },
  { code: "SG", name: "Singapore", description: "Republic of Singapore" },
  { code: "SK", name: "Slovakia", description: "Slovak Republic" },
  { code: "SI", name: "Slovenia", description: "Republic of Slovenia" },
  { code: "SB", name: "Solomon Islands", description: "Solomon Islands" },
  { code: "SO", name: "Somalia", description: "Federal Republic of Somalia" },
  { code: "ZA", name: "South Africa", description: "Republic of South Africa" },
  { code: "SS", name: "South Sudan", description: "Republic of South Sudan" },
  { code: "ES", name: "Spain", description: "Kingdom of Spain" },
  { code: "LK", name: "Sri Lanka", description: "Democratic Socialist Republic of Sri Lanka" },
  { code: "SD", name: "Sudan", description: "Republic of the Sudan" },
  { code: "SR", name: "Suriname", description: "Republic of Suriname" },
  { code: "SE", name: "Sweden", description: "Kingdom of Sweden" },
  { code: "CH", name: "Switzerland", description: "Swiss Confederation" },
  { code: "SY", name: "Syria", description: "Syrian Arab Republic" },
  { code: "TW", name: "Taiwan", description: "Republic of China (Taiwan)" },
  { code: "TJ", name: "Tajikistan", description: "Republic of Tajikistan" },
  { code: "TZ", name: "Tanzania", description: "United Republic of Tanzania" },
  { code: "TH", name: "Thailand", description: "Kingdom of Thailand" },
  { code: "TL", name: "Timor-Leste", description: "Democratic Republic of Timor-Leste" },
  { code: "TG", name: "Togo", description: "Togolese Republic" },
  { code: "TO", name: "Tonga", description: "Kingdom of Tonga" },
  { code: "TT", name: "Trinidad and Tobago", description: "Republic of Trinidad and Tobago" },
  { code: "TN", name: "Tunisia", description: "Republic of Tunisia" },
  { code: "TR", name: "Turkey", description: "Republic of Turkey" },
  { code: "TM", name: "Turkmenistan", description: "Turkmenistan" },
  { code: "TV", name: "Tuvalu", description: "Tuvalu" },
  { code: "UG", name: "Uganda", description: "Republic of Uganda" },
  { code: "UA", name: "Ukraine", description: "Ukraine" },
  { code: "AE", name: "United Arab Emirates", description: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom", description: "United Kingdom of Great Britain and Northern Ireland" },
  { code: "US", name: "United States", description: "United States of America" },
  { code: "UY", name: "Uruguay", description: "Oriental Republic of Uruguay" },
  { code: "UZ", name: "Uzbekistan", description: "Republic of Uzbekistan" },
  { code: "VU", name: "Vanuatu", description: "Republic of Vanuatu" },
  { code: "VA", name: "Vatican City", description: "Vatican City State" },
  { code: "VE", name: "Venezuela", description: "Bolivarian Republic of Venezuela" },
  { code: "VN", name: "Vietnam", description: "Socialist Republic of Vietnam" },
  { code: "YE", name: "Yemen", description: "Republic of Yemen" },
  { code: "ZM", name: "Zambia", description: "Republic of Zambia" },
  { code: "ZW", name: "Zimbabwe", description: "Republic of Zimbabwe" },
  // Territories and Dependencies
  { code: "HK", name: "Hong Kong", description: "Hong Kong Special Administrative Region" },
  { code: "MO", name: "Macau", description: "Macau Special Administrative Region" },
  { code: "PR", name: "Puerto Rico", description: "Commonwealth of Puerto Rico" },
  { code: "GU", name: "Guam", description: "Territory of Guam" },
  { code: "VI", name: "U.S. Virgin Islands", description: "Virgin Islands of the United States" },
  { code: "AS", name: "American Samoa", description: "American Samoa" },
  { code: "BM", name: "Bermuda", description: "Bermuda" },
  { code: "KY", name: "Cayman Islands", description: "Cayman Islands" },
  { code: "VG", name: "British Virgin Islands", description: "British Virgin Islands" },
  { code: "GI", name: "Gibraltar", description: "Gibraltar" },
  { code: "FK", name: "Falkland Islands", description: "Falkland Islands" },
  { code: "GL", name: "Greenland", description: "Greenland" },
  { code: "FO", name: "Faroe Islands", description: "Faroe Islands" },
  { code: "AW", name: "Aruba", description: "Aruba" },
  { code: "CW", name: "Curaçao", description: "Curaçao" },
  { code: "SX", name: "Sint Maarten", description: "Sint Maarten" },
  { code: "NC", name: "New Caledonia", description: "New Caledonia" },
  { code: "PF", name: "French Polynesia", description: "French Polynesia" },
  { code: "GG", name: "Guernsey", description: "Bailiwick of Guernsey" },
  { code: "JE", name: "Jersey", description: "Bailiwick of Jersey" },
  { code: "IM", name: "Isle of Man", description: "Isle of Man" },
];

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get auth header
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Create Supabase client
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    // Verify user
    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsError || !claimsData?.claims) {
      return new Response(
        JSON.stringify({ error: "Invalid token" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const userId = claimsData.claims.sub;

    // Prepare data for insertion with user_id and list_type
    const currencyRecords = currencies.map((c, idx) => ({
      user_id: userId,
      list_type: "currencies",
      code: c.code,
      name: c.name,
      description: c.description,
      display_order: idx + 1,
      is_active: true,
    }));

    const bankRecords = banks.map((b, idx) => ({
      user_id: userId,
      list_type: "banks",
      code: b.code,
      name: b.name,
      description: b.description,
      display_order: idx + 1,
      is_active: true,
    }));

    const locationRecords = locations.map((l, idx) => ({
      user_id: userId,
      list_type: "locations",
      code: l.code,
      name: l.name,
      description: l.description,
      display_order: idx + 1,
      is_active: true,
    }));

    // Insert currencies
    const { error: currError } = await supabase
      .from("admin_general_lists")
      .upsert(currencyRecords, { onConflict: "user_id,list_type,code", ignoreDuplicates: true });

    if (currError) {
      console.error("Currency insert error:", currError);
    }

    // Insert banks
    const { error: bankError } = await supabase
      .from("admin_general_lists")
      .upsert(bankRecords, { onConflict: "user_id,list_type,code", ignoreDuplicates: true });

    if (bankError) {
      console.error("Bank insert error:", bankError);
    }

    // Insert locations
    const { error: locError } = await supabase
      .from("admin_general_lists")
      .upsert(locationRecords, { onConflict: "user_id,list_type,code", ignoreDuplicates: true });

    if (locError) {
      console.error("Location insert error:", locError);
    }

    const hasErrors = currError || bankError || locError;

    return new Response(
      JSON.stringify({
        success: !hasErrors,
        message: hasErrors 
          ? "Some data may not have been inserted" 
          : "Reference data seeded successfully",
        counts: {
          currencies: currencies.length,
          banks: banks.length,
          locations: locations.length,
        },
      }),
      { 
        status: hasErrors ? 207 : 200, 
        headers: { ...corsHeaders, "Content-Type": "application/json" } 
      }
    );
  } catch (error) {
    console.error("Seed error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
